export const TESTIMONIALS = [
    {
        name: "Beatric Leeman",
        role: "COO",
        company: "makeupease",
        companyUrl: "https://mailchimp.com",
        image: "/images/testimonials/person1.jpg",
        content: "It's intuitive, functional, easy-to-setup.",
        time: "3:45 PM",
        date: "may 02, 2025",
    },
    {
        name: "Ekay Gabriel",
        role: "Founder",
        company: "Ziva",
        companyUrl: "https://mailchimp.com",
        image: "/images/testimonials/person2.jpg",
        content: "The platform made our budgeting seamless and efficient.",
        time: "11:10 AM",
        date: "may 17, 2024",
    },
    {
        name: "John Ita",
        role: "Product Manager",
        company: "moodify",
        companyUrl: "https://google.com",
        image: "/images/testimonials/person3.jpg",
        content: "This tool has transformed the way we track & manage our business expense.",
        time: "9:30 AM",
        date: "sept 15, 2025",
    },
    {
        name: "Grace mensah",
        role: "Accountant",
        company: "rb structures",
        companyUrl: "https://microsoft.com",
        image: "/images/testimonials/person4.jpg",
        content: "A game-changer for our Accounting team.",
        time: "2:00 PM",
        date: "oct 01, 2025",
    },
    {
        name: "Michael kojo",
        role: "Founder",
        company: "recpro",
        companyUrl: "https://adobe.com",
        image: "/images/testimonials/person1.jpg",
        content: "Trackify is a great helping in tracking my crypto stocks and investments.",
        time: "4:15 PM",
        date: "Oct 01, 2025",
    },
    {
        name: "Olivia Brown",
        role: "Data Analyst",
        company: "RCA",
        companyUrl: "https://ibm.com",
        image: "/images/testimonials/person2.jpg",
        content: "Incredible insights and analytics, a must-have for any data team.",
        time: "1:20 PM",
        date: "oct 02, 2025",
    },
];
