export const TESTIMONIALS = [
    {
        name: "Sarah Leeman",
        role: "Marketing Leader",
        company: "Mailchimp",
        companyUrl: "https://mailchimp.com",
        image: "/images/testimonials/person1.jpg",
        content: "It's intuitive, functional, easy-to-setup and presents content beautifully.",
        time: "3:45 PM",
        date: "Jun 20, 2024",
    },
    {
        name: "Amaya Locosta",
        role: "Marketing Leader",
        company: "Mailchimp",
        companyUrl: "https://mailchimp.com",
        image: "/images/testimonials/person2.jpg",
        content: "The platform made our workflow seamless and efficient.",
        time: "11:10 AM",
        date: "Jul 2, 2024",
    },
    {
        name: "John Doe",
        role: "Product Manager",
        company: "Google",
        companyUrl: "https://google.com",
        image: "/images/testimonials/person3.jpg",
        content: "This tool has transformed the way we manage our projects.",
        time: "9:30 AM",
        date: "Aug 15, 2023",
    },
    {
        name: "Emily Johnson",
        role: "Software Engineer",
        company: "Microsoft",
        companyUrl: "https://microsoft.com",
        image: "/images/testimonials/person4.jpg",
        content: "A game-changer for our development team, highly recommend!",
        time: "2:00 PM",
        date: "Sep 5, 2024",
    },
    {
        name: "Michael Smith",
        role: "UX Designer",
        company: "Adobe",
        companyUrl: "https://adobe.com",
        image: "/images/testimonials/person1.jpg",
        content: "The design capabilities are top-notch, making our work so much easier.",
        time: "4:15 PM",
        date: "Oct 10, 2024",
    },
    {
        name: "Olivia Brown",
        role: "Data Analyst",
        company: "IBM",
        companyUrl: "https://ibm.com",
        image: "/images/testimonials/person2.jpg",
        content: "Incredible insights and analytics, a must-have for any data team.",
        time: "1:20 PM",
        date: "Nov 25, 2024",
    },
];
